apiVersion: v2
description: Customer Registry GraphQL Service
name: ffc-customer-registry-api
# this version is automatically updated in the build pipeline
version: 1.0.1
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
