version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      lint:
        patterns:
          - 'prettier'
          - 'eslint'
          - 'eslint-*'

      logging:
        patterns:
          - '*-winston'
          - '*-winston-format'
          - 'winston'
          - 'winston-*'

      tools:
        patterns:
          - 'husky'
          - 'jest'
          - 'nodemon'

      types:
        patterns:
          - '@types/*'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
