version: '3.4'
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - fcp-dal

  ################################################################################

  fcp-dal-api:
    build: ./
    container_name: fcp-dal-api
    ports:
      - '3555:3555'
    # links:
    #   - 'localstack:localstack'
    # depends_on:
    #   localstack:
    #     condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3555
      NODE_ENV: development # overridden for friendlier logging
      # LOCALSTACK_ENDPOINT: http://localstack:4566
    networks:
      - fcp-dal

################################################################################

networks:
  fcp-dal:
    driver: bridge
