# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-customer-registry-api:
    build:
      target: development
    image: ffc-customer-registry-api-development
    container_name: ffc-customer-registry-api-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./mocks:/home/node/mocks
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_ENV: development
      ENABLE_MOCK_SERVER: true
      PORT_MOCK: 3100
      RURAL_PAYMENTS_AGENCY_LAND_API_URL: https://environment.data.gov.uk
      RURAL_PAYMENTS_PORTAL_API_URL: http://localhost:3100/rpp/
      RURAL_PAYMENTS_PORTAL_EMAIL: some-email
