services:
  ffc-customer-registry-api:
    image: node:18
    container_name: ffc-customer-registry-api-dev
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    volumes:
      - ./:/usr/local/dev/ffc-customer-registry-api
    working_dir: /usr/local/dev/ffc-customer-registry-api
    environment:
      RURAL_PAYMENTS_AGENCY_LAND_API_URL: https://environment.data.gov.uk
      RURAL_PAYMENTS_PORTAL_API_URL: http://localhost:3100/rpp/
      RURAL_PAYMENTS_PORTAL_EMAIL: some-email
    env_file:
      - .env