name: fcp-data-access-layer-api
namespace: ffc-dal
image: fcp-data-access-layer-api

labels: {}

deployment:
  priorityClassName: low
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 5

service:
  port: 80
  type: ClusterIP
  
container:
  memCpuTier: XL
  imagePullPolicy: IfNotPresent
  # Only used if memCpuTier set to CUSTOM
  # requestMemory: 50Mi
  # requestCpu: 50m
  # limitMemory: 200Mi
  # limitCpu: 400m
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
  port: 3000

ingress:
  class: nginx
  endpoint: ffc-dal
  server: example.com

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
  script: /home/node/scripts/healthz

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-dal
  roleArn: true
