- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3000"
- key: REST_CLIENT_TIMEOUT_IN_MILLIS
  value: "20000"
- key: STATIC_CACHE_TIMEOUT_IN_MILLIS
  value: "54000"  
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"            
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"